CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(128),
  display_name VARCHAR(64),
  role VARCHAR(32) NOT NULL DEFAULT 'viewer',
  status TINYINT NOT NULL DEFAULT 0,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skill (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  description VARCHAR(512),
  runtime VARCHAR(32) NOT NULL DEFAULT 'python',
  git_repo_path VARCHAR(512),
  current_version VARCHAR(32) DEFAULT '0.0.0',
  draft_revision BIGINT NOT NULL DEFAULT 0,
  status VARCHAR(32) DEFAULT 'draft',
  visibility VARCHAR(16) NOT NULL DEFAULT 'private',
  entry_file VARCHAR(256) DEFAULT 'scripts/main.py',
  target_platforms VARCHAR(256),
  dependency_summary CLOB,
  creator_id BIGINT,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_skill_name UNIQUE(name, is_deleted)
);

CREATE TABLE IF NOT EXISTS team (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL UNIQUE,
  description VARCHAR(512),
  owner_id BIGINT NOT NULL,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS team_member (
  team_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  member_role VARCHAR(32) NOT NULL DEFAULT 'member',
  PRIMARY KEY (team_id, user_id)
);

CREATE TABLE IF NOT EXISTS skill_template (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  description VARCHAR(512),
  scope VARCHAR(16) NOT NULL DEFAULT 'team',
  team_id BIGINT,
  creator_id BIGINT,
  content CLOB NOT NULL,
  version VARCHAR(32) NOT NULL DEFAULT '1.0.0',
  is_deleted TINYINT NOT NULL DEFAULT 0,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS git_credential (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL,
  name VARCHAR(128) NOT NULL,
  repo_url VARCHAR(512) NOT NULL,
  auth_type VARCHAR(32) NOT NULL,
  username VARCHAR(128),
  secret_ciphertext CLOB,
  creator_id BIGINT NOT NULL,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skill_version (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill_id BIGINT NOT NULL,
  version VARCHAR(32) NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  source_ref VARCHAR(256),
  change_summary VARCHAR(512),
  snapshot_path VARCHAR(512),
  creator_id BIGINT NOT NULL,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skill_review (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill_id BIGINT NOT NULL,
  version_id BIGINT,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  comment VARCHAR(1024),
  applicant_id BIGINT NOT NULL,
  reviewer_id BIGINT,
  debug_result CLOB,
  debug_passed TINYINT,
  debug_input CLOB,
  total_tokens INT,
  test_case_count INT,
  test_pass_count INT,
  debug_summary VARCHAR(512),
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS agent (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  description VARCHAR(512),
  current_version VARCHAR(32) DEFAULT '0.0.0',
  status VARCHAR(32) DEFAULT 'draft',
  model_name VARCHAR(128),
  system_prompt CLOB,
  canvas_config CLOB,
  creator_id BIGINT,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_agent_name UNIQUE(name, is_deleted)
);

CREATE TABLE IF NOT EXISTS sub_agent (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id BIGINT NOT NULL,
  name VARCHAR(128) NOT NULL,
  description VARCHAR(512),
  system_prompt CLOB NOT NULL,
  model_name VARCHAR(128),
  is_deleted TINYINT NOT NULL DEFAULT 0,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skill_mounting (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id BIGINT NOT NULL,
  sub_agent_id BIGINT,
  skill_id BIGINT NOT NULL,
  skill_alias VARCHAR(128),
  agent_version VARCHAR(32),
  enabled TINYINT NOT NULL DEFAULT 1,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS agent_version (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id BIGINT NOT NULL,
  version VARCHAR(32) NOT NULL,
  change_summary VARCHAR(512),
  creator_id BIGINT NOT NULL,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_agent_version UNIQUE(agent_id, version)
);

CREATE TABLE IF NOT EXISTS skill_operation_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill_id BIGINT NOT NULL,
  operator_id BIGINT NOT NULL,
  operator_name VARCHAR(64) NOT NULL,
  action VARCHAR(32) NOT NULL,
  description VARCHAR(512),
  change_summary VARCHAR(2048),
  status VARCHAR(16) NOT NULL DEFAULT 'success',
  version VARCHAR(32),
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS eval_task (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  agent_id BIGINT NOT NULL,
  agent_version VARCHAR(32),
  dataset_key VARCHAR(64) NOT NULL,
  dataset_version VARCHAR(32),
  scope VARCHAR(32) DEFAULT 'all',
  status VARCHAR(32) DEFAULT 'pending',
  result_summary CLOB,
  creator_id BIGINT,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pipeline (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  description VARCHAR(512),
  type VARCHAR(32) DEFAULT 'factory',
  stages CLOB NOT NULL,
  current_version VARCHAR(32) DEFAULT '0.0.0',
  status VARCHAR(32) DEFAULT 'draft',
  creator_id BIGINT,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_pipeline_name UNIQUE(name, is_deleted)
);

MERGE INTO sys_user (username, password, display_name, role, status, is_deleted)
KEY(username) VALUES
  ('admin', 'admin123', '系统管理员', 'admin', 0, 0),
  ('developer', 'dev123', 'Skill 开发者', 'developer', 0, 0),
  ('qa', 'qa123', '测试工程师', 'qa', 0, 0);

MERGE INTO team (id, name, description, owner_id) KEY(id) VALUES
  (1, '默认研发团队', '本地联调默认团队', 1);
MERGE INTO team_member (team_id, user_id, member_role) KEY(team_id, user_id) VALUES
  (1, 1, 'admin'), (1, 2, 'member'), (1, 3, 'member');

-- 本地联调 Mock：用于验证“智能体 -> 版本”两级下拉联动。
MERGE INTO agent (id, name, description, current_version, status, model_name, system_prompt, creator_id, is_deleted)
KEY(id) VALUES
  (1001, '客户服务助手', '处理客户咨询、知识检索与工单分流', '1.2.0', 'active', 'qwen3.7-max', '你是客户服务助手。', 1, 0),
  (1002, '运营分析助手', '处理指标查询、趋势分析与摘要生成', '2.1.0', 'active', 'qwen3.7-plus', '你是运营分析助手。', 1, 0),
  (1003, '文档审核助手', '处理文档要素检查、风险提示与修改建议', '0.9.0', 'testing', 'qwen3.6-flash', '你是文档审核助手。', 1, 0);

MERGE INTO agent_version (id, agent_id, version, change_summary, creator_id) KEY(id) VALUES
  (1101, 1001, '1.0.0', '基础问答与知识检索', 1),
  (1102, 1001, '1.1.0', '增加工单分流', 1),
  (1103, 1001, '1.2.0', '优化多轮上下文', 1),
  (1201, 1002, '2.0.0', '指标查询与摘要', 1),
  (1202, 1002, '2.1.0', '增加趋势对比', 1),
  (1301, 1003, '0.8.0', '文档要素检查', 1),
  (1302, 1003, '0.9.0', '增加风险分级提示', 1);
